// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf_1gcQqMqIpZWZ7c1HSnmfq1DWiQJMpY',
    appId: '1:263659234453:web:43b22b7cb2da9b1b0de79c',
    messagingSenderId: '263659234453',
    projectId: 'pasakay-toda-dispatch',
    authDomain: 'pasakay-toda-dispatch.firebaseapp.com',
    storageBucket: 'pasakay-toda-dispatch.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf_1gcQqMqIpZWZ7c1HSnmfq1DWiQJMpY',
    appId: '1:263659234453:web:43b22b7cb2da9b1b0de79c',
    messagingSenderId: "263659234453",
    projectId: "pasakay-toda-dispatch",
    storageBucket: "pasakay-toda-dispatch.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf_1gcQqMqIpZWZ7c1HSnmfq1DWiQJMpY',
    appId: '1:263659234453:ios:43b22b7cb2da9b1b0de79c',
    messagingSenderId: '263659234453',
    projectId: 'pasakay-toda-dispatch',
    storageBucket: 'pasakay-toda-dispatch.firebasestorage.app',
    iosBundleId: 'com.pasakay.toda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf_1gcQqMqIpZWZ7c1HSnmfq1DWiQJMpY',
    appId: '1:263659234453:macos:43b22b7cb2da9b1b0de79c',
    messagingSenderId: '263659234453',
    projectId: 'pasakay-toda-dispatch',
    storageBucket: 'pasakay-toda-dispatch.firebasestorage.app',
    iosBundleId: 'com.pasakay.toda',
  );
}
