// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyARP02JNcdIbF4kMk9muvrn9vftcchZ4rE",
    authDomain: "pasakaytoda-bbb90.firebaseapp.com",
    projectId: "pasakaytoda-bbb90",
    storageBucket: "pasakaytoda-bbb90.firebasestorage.app",
    messagingSenderId: "503527035016",
    appId: "1:503527035016:android:4c929baa3b306353e60f3d",
    measurementId: "G-CTJRVR4DVC",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyARP02JNcdIbF4kMk9muvrn9vftcchZ4rE",
    authDomain: "pasakaytoda-bbb90.firebaseapp.com",
    projectId: "pasakaytoda-bbb90",
    storageBucket: "pasakaytoda-bbb90.firebasestorage.app",
    messagingSenderId: "503527035016",
    appId: "1:503527035016:android:4c929baa3b306353e60f3d",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBd014rhHg1NLj8noa-AW7bkztf_MzmLF4",
    authDomain: "pasakay-toda-.firebaseapp.com",
    projectId: "pasakay-v1",
    storageBucket: "pasakay-toda.firebasestorage.app",
    messagingSenderId: "563584335869",
    appId: "1:563584335869:ios:YOUR_IOS_APP_ID_HERE",
    measurementId: "G-CTJRVR4DVC",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBd014rhHg1NLj8noa-AW7bkztf_MzmLF4",
    authDomain: "pasakay-toda-.firebaseapp.com",
    projectId: "pasakay-v1",
    storageBucket: "pasakay-toda.firebasestorage.app",
    messagingSenderId: "563584335869",
    appId: "1:563584335869:macos:YOUR_MACOS_APP_ID_HERE",
    measurementId: "G-CTJRVR4DVC",
  );
}
